language: php

php:
  - 7.3
  - 8.0

before_script:
  - mkdir shyffon
  - composer update
  - composer install --prefer-source --no-interaction

script:
  - phpunit System/Test/SimpleTest.php

env:
  - APP_ENV=development
  - APP_DIR=shyffon
  - DB_CONNECTION=mysql
